name: tempher
description: A app to track the current weather and the forecast
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_modular: ^6.0.4+1
  flutter_svg: ^2.0.7
  package_info_plus: ^4.1.0
  easy_localization: ^3.0.2
  lucide_icons: ^0.257.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  wakelock_plus: ^1.1.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/Gilroy-Semibold.ttf
          weight: 600
        - asset: assets/fonts/Gilroy-Medium.ttf
          weight: 400
